In [45]:
print("hi")

hi


In [17]:
import array
a=array.array('i',[1,2,3,4,5,6])
for i in range (0,6):
    ab=array.array('l',[6,9,3,78,5,2,6,])
    for l in range (0,7):
        print(ab[l])
    print(a[i])

6
9
3
78
5
2
6
1
6
9
3
78
5
2
6
2
6
9
3
78
5
2
6
3
6
9
3
78
5
2
6
4
6
9
3
78
5
2
6
5
6
9
3
78
5
2
6
6


In [6]:
import array
arr=array.array('i',[1,2,3,4,5,6])
arr.append(50)
print(arr)

#sort
arr12=array.array('i',sorted(arr))
print(arr12)

newarr=arr.tolist()
print(newarr)

array('i', [1, 2, 3, 4, 5, 6, 50])
array('i', [1, 2, 3, 4, 5, 6, 50])
[1, 2, 3, 4, 5, 6, 50]


In [5]:
import numpy as np
arr1=np.array([[1,4,4],[4,3,8]])
print(arr1.shape)


(2, 3)


In [3]:
import numpy as np
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar2.shape)

(3, 3)


In [10]:
a1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a1.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [24]:
a2=np.array([[2,3,4],[5,3,7]])
print(a2.ndim)

2


In [18]:
a3=np.array([2,4,7,5,3,6,9,5,3,9])
print(a3.dtype)

int64


In [28]:
a4=np.array([2,3,4,7,2,6,8,7,9])
print(a4.size)

9


In [36]:
a5=np.array([[2,3,4,5],[6,7,8,9]])
print(a5[1][2])
print(a5)

8
[[2 3 4 5]
 [6 7 8 9]]


In [44]:
a6=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(a6[1][1])
print("-----------")
print(a6)
print("*********")
print(a6[0:1])
print("*********")
print(a6[:,1])
print("*********")

7
-----------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
*********
[[1 2 3 4 5]]
*********
[ 2  7 12]
*********


In [47]:
b=np.array([1,2,3])

print(b+2)
print(b*2)

[3 4 5]
[2 4 6]


In [51]:
b1=np.array([2,4,6,8])
print(np.sum(b1))
print(np.mean(b1))
print(np.median(b1))
print(np.max(b1))
print(np.min(b1))

20
5.0
5.0
8
2


In [52]:
b2=np.array([7,2,7,9,3,7,4,2,6,9,2,6])
print(np.median(b2))

6.0


In [58]:
a=np.array([1,2,3,4,5,6])
b=a.reshape([2,3])
print(b)
print(np.flatten(a))

[[1 2 3]
 [4 5 6]]


AttributeError: module 'numpy' has no attribute 'flatten'