In [4]:
import numpy as np

arr1=np.array([1,2,3,4,5,6])
arr2=np.array([3,6,9,2,4,8])

sum=arr1+arr2
product= arr1 * arr2

print(f"the sum of {arr1} and {arr2} is : ",sum)
print(f"the product of {arr1} and {arr2} is :",product)

the sum of [1 2 3 4 5 6] and [3 6 9 2 4 8] is :  [ 4  8 12  6  9 14]
the product of [1 2 3 4 5 6] and [3 6 9 2 4 8] is : [ 3 12 27  8 20 48]


In [8]:
import numpy as np

arr1=np.array([[1,2,3],
              [4,6,3]])
arr2=np.array([[3,6,9],
              [2,4,8]])

sum=arr1+arr2
funcsum=np.add(arr1, arr2)

product=arr1*arr2
funcpro=np.multiply(arr1, arr2)

print(f"the sum of {arr1} and {arr2} is :", sum)
print(f"the sum of {arr1} and {arr2} is using function :", funcsum)

print(f"the product of {arr1} and {arr2} is :",product)
print(f"the product of {arr1} and {arr2} is :",funcpro)

the sum of [[1 2 3]
 [4 6 3]] and [[3 6 9]
 [2 4 8]] is : [[ 4  8 12]
 [ 6 10 11]]
the sum of [[1 2 3]
 [4 6 3]] and [[3 6 9]
 [2 4 8]] is using function : [[ 4  8 12]
 [ 6 10 11]]
the product of [[1 2 3]
 [4 6 3]] and [[3 6 9]
 [2 4 8]] is : [[ 3 12 27]
 [ 8 24 24]]
the product of [[1 2 3]
 [4 6 3]] and [[3 6 9]
 [2 4 8]] is : [[ 3 12 27]
 [ 8 24 24]]


In [15]:
arr=np.array([[1,2,3],
              [4,6,3]])
print(arr)
print(np.shape(arr))

arra_func=np.transpose(arr)
print(arra_func)

[[1 2 3]
 [4 6 3]]
(2, 3)
[[1 4]
 [2 6]
 [3 3]]


In [17]:
import numpy as np

arr1=np.array([[1,2,3],
              [4,6,3]])
arr2=np.array([[3,6,9],
              [2,4,8]])

sub=arr1-arr2
sub1=np.subtract(arr1, arr2)

print(f"the difference of {arr1} and {arr2} is : ", sub)
print(f"the difference using sum is: ", sub1)

the difference of [[1 2 3]
 [4 6 3]] and [[3 6 9]
 [2 4 8]] is :  [[-2 -4 -6]
 [ 2  2 -5]]
the difference using sum is:  [[-2 -4 -6]
 [ 2  2 -5]]


In [28]:
import numpy as np

mat1=np.array([[1,2,3],
              [4,6,3]])
mat2=np.array([[3,6],
              [2,4],
              [6,9]])

print(np.shape(mat1))
print(np.shape(mat2))

dot=np.dot(mat1, mat2)
trans=np.transpose(mat1)

print("the product is:",dot)
print(trans)

(2, 3)
(3, 2)
the product is: [[25 41]
 [42 75]]
[[1 4]
 [2 6]
 [3 3]]


In [27]:
import numpy as np

mat1=np.array([[1,2,3],
              [4,6,3]])
mat2=np.array([[3,6,9],
              [2,4,8]])

print(np.shape(mat1))
print(np.shape(mat2))

sum=np.add(mat1, mat2)
pro=np.multiply(mat1, mat2)

print(sum)
print(pro)

(2, 3)
(2, 3)
[[ 4  8 12]
 [ 6 10 11]]
[[ 3 12 27]
 [ 8 24 24]]


In [26]:
import numpy as np

arr1=np.array([1,2,3,4,5,6])
arr2=np.array([3,6,9,2,4,8])

quo=np.divide(arr1, arr2)

print(f"The quotent of {arr1} and {arr2} is :", quo)

The quotent of [1 2 3 4 5 6] and [3 6 9 2 4 8] is : [0.33333333 0.33333333 0.33333333 2.         1.25       0.75      ]


In [31]:
import numpy as np

arr1=np.array([1,2,3,4,5,6])
arr2=np.array([3,6,9,2,4,8])

mo=np.mod(arr1, arr2)
pow=np.power(arr1, arr2)
abs=np.absolute(arr1, arr2)
neg=np.negative(arr1, arr2)

print("the modulus is:", mo)
print("The power is:", pow)
print("the absolute is ", abs)
print("the negative is:", neg)

the modulus is: [1 2 3 0 1 6]
The power is: [      1      64   19683      16     625 1679616]
the absolute is  [-1 -2 -3 -4 -5 -6]
the negative is: [-1 -2 -3 -4 -5 -6]


In [40]:
file1=open("hello1.txt","w")
file1.write("hi hello this is me who am i")
file1.close()

In [41]:
file1=open("hell1.txt","x")
file1.write("hi hello this is me who am i")
file1.close()

In [42]:
file1=open("hell1.txt","a")
file1.write("ide haadu ide bhashe endendu haage ye irali hege irali yene irali ")
file1.close()

In [44]:
file1=open("hell1.txt","r")
file1.read()
file1.close()

In [45]:
with open("hell1.txt","r") as file:
    print(file.read())

hi hello this is me who am iide haadu ide bhashe endendu haage ye irali hege irali yene irali 


In [48]:
with open("helli1.txt","x") as file:
    print(file.write("kannada songs"))

13


In [49]:
with open("helli1.txt","w") as file:
    print(file.write("new kannada songs"))
with open("helli1.txt","r") as file:
    print(file.read())

17
new kannada songs


In [51]:
import csv

with open("Untitled spreadsheet - Sheet1 (1).csv", "r") as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['songs', 'rating']
['manasa', '1000']
['endu kanada', '1000']
['ide hadu', '1000']
['aarathiye', '1000']
['beladingalagi ba', '1000']


In [1]:
with open("helli1.txt","a") as file:
    print(file.write("newly added content, do not overwrite existing content"))
with open("helli1.txt","r") as file:
    print(file.read())

54
new kannada songsnewly added content, do not overwrite existing content


In [3]:
with open("filenew.txt","x") as file:   # create file
    print(file.write("this is read and write mode"))
with open("filenew.txt","r+") as file:   # for read and write
    print(file.read())
    print(file.write("added content"))

27
this is read and write mode
13
